"""Major migrate

Revision ID: 83046badb1e7
Revises: 
Create Date: 2025-02-05 12:42:36.245499

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "83046badb1e7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "professions",
        sa.Column("title", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_professions")),
    )
    op.create_table(
        "users_roles",
        sa.Column("title", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users_roles")),
    )
    op.create_table(
        "users",
        sa.Column("first_name", sa.String(length=32), nullable=False),
        sa.Column("second_name", sa.String(length=32), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=32), nullable=False),
        sa.Column("birthday", sa.Date(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column(
            "time_created",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["users_roles.id"],
            name=op.f("fk_users_role_id_users_roles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_table(
        "experiences",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("prof_id", sa.Integer(), nullable=False),
        sa.Column("years", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["prof_id"],
            ["professions.id"],
            name=op.f("fk_experiences_prof_id_professions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_experiences_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experiences")),
    )
    op.create_table(
        "projects",
        sa.Column("title", sa.String(length=32), nullable=False),
        sa.Column("desc", sa.String(length=256), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_projects_owner_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_table(
        "projects_workers",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_projects_workers_project_id_projects"),
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["users.id"],
            name=op.f("fk_projects_workers_worker_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects_workers")),
    )
    with open('./app/utils/professions.txt', 'r', encoding="utf-8") as file:
        print("start reading file")
        lines = file.readlines()
        for line in lines:
            op.execute("INSERT INTO professions (title) VALUES ('" + line[:-1] + "')")
        op.execute("INSERT INTO users_roles (id, title) VALUES (1, 'Админ'), (2, 'Работник'), (3, 'ГИП')")
        op.execute("INSERT INTO users (first_name, second_name, phone, email, birthday, role_id) VALUES ('АДМИН', 'АДМИНЫЧ', '+7(999)999-99-99', 'admin@mail.ru', '1111-11-11', 1)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("projects_workers")
    op.drop_table("projects")
    op.drop_table("experiences")
    op.drop_table("users")
    op.drop_table("users_roles")
    op.drop_table("professions")
    # ### end Alembic commands ###
